# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98930868505cd81034e822b4c63b4824a0382d6564727eeca1eceaac54ee40057b60584e907310a35273b931d1c87e306803222010025c3b5482b2c03ea88fb4

test:
  secret_key_base: fa82dd024696c05310cda0bb362ded4bb829f659f59022be3cb30dbf5cb71561e1609450e3cfa15b4056bf3e32dc19249ba75383534a47dddd4109fe08543f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
